name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Login to docker hub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        
      - name: Build docker image
        run: docker build -t kangwookyoo/docker-cicd .
      - name: Publish image to docker hub
        run: docker push kangwookyoo/docker-cicd:latest

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull Image from docker hub
        run: docker pull kangwookyoo/docker-cicd:latest
      - name: Delete old container
        run: docker rm -f docker-cicd-container
      - name: Run docker container
        run: docker run -d -p 8080:8080 --name docker-cicd-container kangwookyoo/docker-cicd
